package com.kyrgyzexplore.booking;

import com.kyrgyzexplore.booking.dto.CreateBookingRequest;
import com.kyrgyzexplore.common.exception.AppException;
import com.kyrgyzexplore.config.StripeConfig;
import com.kyrgyzexplore.email.EmailService;
import com.kyrgyzexplore.listing.Listing;
import com.kyrgyzexplore.listing.ListingRepository;
import com.kyrgyzexplore.notification.NotificationService;
import com.kyrgyzexplore.payment.PaymentService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

/**
 * Unit tests for BookingService business rules.
 *
 * WHY use @ExtendWith(MockitoExtension.class) instead of @SpringBootTest?
 * @SpringBootTest loads the full application context (DB, Redis, Stripe, Firebase).
 * That's slow (~10 s) and requires all infrastructure to be running.
 * Unit tests should be fast and isolated — Mockito fakes provide only what we need.
 *
 * WHY ReflectionTestUtils.setField() for ids and DTO fields?
 * BaseEntity.id has no setter (auto-generated by JPA in production).
 * Request DTOs are @Getter-only (Jackson deserialises them without setters).
 * ReflectionTestUtils lets tests set those private fields without changing
 * production code, which would pollute the real API just for test convenience.
 */
@ExtendWith(MockitoExtension.class)
class BookingServiceTest {

    @Mock private BookingRepository bookingRepository;
    @Mock private ListingRepository listingRepository;
    @Mock private PaymentService paymentService;
    @Mock private StripeConfig stripeConfig;
    @Mock private NotificationService notificationService;
    @Mock private EmailService emailService;

    @InjectMocks
    private BookingService bookingService;

    private final UUID HOST_ID     = UUID.randomUUID();
    private final UUID TRAVELER_ID = UUID.randomUUID();
    private final UUID LISTING_ID  = UUID.randomUUID();

    private Listing listing;

    @BeforeEach
    void setUp() {
        listing = Listing.builder()
                .hostId(HOST_ID)
                .title("Cozy Apartment in Bishkek")
                .pricePerUnit(new BigDecimal("2000.00"))
                .maxGuests(4)
                .build();
        ReflectionTestUtils.setField(listing, "id", LISTING_ID);
        listing.setActive(true);
    }

    // ── Date validation ───────────────────────────────────────────────────────

    @Test
    void create_throwsWhenCheckOutBeforeCheckIn() {
        when(listingRepository.findByIdForBooking(LISTING_ID))
                .thenReturn(Optional.of(listing));

        CreateBookingRequest req = request(
                LocalDate.of(2026, 6, 10),
                LocalDate.of(2026, 6, 5)   // before check-in
        );

        assertThatThrownBy(() -> bookingService.create(TRAVELER_ID, req))
                .isInstanceOf(AppException.class)
                .hasMessageContaining("Check-out date must be after check-in date");
    }

    @Test
    void create_throwsWhenCheckOutEqualToCheckIn() {
        when(listingRepository.findByIdForBooking(LISTING_ID))
                .thenReturn(Optional.of(listing));

        CreateBookingRequest req = request(
                LocalDate.of(2026, 6, 10),
                LocalDate.of(2026, 6, 10)  // same day = 0 nights
        );

        assertThatThrownBy(() -> bookingService.create(TRAVELER_ID, req))
                .isInstanceOf(AppException.class)
                .hasMessageContaining("Check-out date must be after check-in date");
    }

    // ── Self-booking prevention ───────────────────────────────────────────────

    @Test
    void create_throwsWhenHostTriesToBookOwnListing() {
        when(listingRepository.findByIdForBooking(LISTING_ID))
                .thenReturn(Optional.of(listing));

        CreateBookingRequest req = request(
                LocalDate.of(2026, 6, 10),
                LocalDate.of(2026, 6, 13)
        );

        assertThatThrownBy(() -> bookingService.create(HOST_ID, req))
                .isInstanceOf(AppException.class)
                .hasMessageContaining("cannot book your own listing");
    }

    // ── Guest count validation ────────────────────────────────────────────────

    @Test
    void create_throwsWhenGuestsExceedMax() {
        when(listingRepository.findByIdForBooking(LISTING_ID))
                .thenReturn(Optional.of(listing));

        // listing.maxGuests = 4; request 5
        CreateBookingRequest req = requestWithGuests(
                LocalDate.of(2026, 6, 10),
                LocalDate.of(2026, 6, 13),
                5
        );

        assertThatThrownBy(() -> bookingService.create(TRAVELER_ID, req))
                .isInstanceOf(AppException.class)
                .hasMessageContaining("accommodates at most 4 guests");
    }

    // ── Price calculation ─────────────────────────────────────────────────────

    @Test
    void create_calculatesNightlyPriceCorrectly() {
        when(listingRepository.findByIdForBooking(LISTING_ID))
                .thenReturn(Optional.of(listing));
        when(bookingRepository.existsConflict(any(), any(), any(), any()))
                .thenReturn(false);
        when(bookingRepository.save(any())).thenAnswer(inv -> {
            Booking b = inv.getArgument(0);
            ReflectionTestUtils.setField(b, "id", UUID.randomUUID());
            return b;
        });
        when(listingRepository.findByIdAndDeletedAtIsNull(LISTING_ID))
                .thenReturn(Optional.of(listing));

        // 3 nights × 2000 KGS = 6000 KGS
        CreateBookingRequest req = request(
                LocalDate.of(2026, 6, 10),
                LocalDate.of(2026, 6, 13)
        );

        var response = bookingService.create(TRAVELER_ID, req);

        assertThat(response.getTotalPrice())
                .isEqualByComparingTo(new BigDecimal("6000.00"));
        assertThat(response.getNightCount()).isEqualTo(3L);
    }

    // ── Status transitions ────────────────────────────────────────────────────

    @Test
    void confirm_throwsWhenBookingIsNotPending() {
        Booking booking = bookingWithStatus(BookingStatus.CONFIRMED);
        when(bookingRepository.findById(booking.getId()))
                .thenReturn(Optional.of(booking));
        when(listingRepository.findByIdAndDeletedAtIsNull(LISTING_ID))
                .thenReturn(Optional.of(listing));

        assertThatThrownBy(() -> bookingService.confirm(booking.getId(), HOST_ID))
                .isInstanceOf(AppException.class)
                .hasMessageContaining("Only PENDING bookings can be confirmed");
    }

    @Test
    void reject_throwsWhenBookingIsAlreadyRejected() {
        Booking booking = bookingWithStatus(BookingStatus.REJECTED);
        when(bookingRepository.findById(booking.getId()))
                .thenReturn(Optional.of(booking));
        when(listingRepository.findByIdAndDeletedAtIsNull(LISTING_ID))
                .thenReturn(Optional.of(listing));

        assertThatThrownBy(() -> bookingService.reject(booking.getId(), HOST_ID, "No availability"))
                .isInstanceOf(AppException.class)
                .hasMessageContaining("Only PENDING bookings can be rejected");
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private CreateBookingRequest request(LocalDate checkIn, LocalDate checkOut) {
        return requestWithGuests(checkIn, checkOut, 2);
    }

    private CreateBookingRequest requestWithGuests(
            LocalDate checkIn, LocalDate checkOut, int guests) {
        CreateBookingRequest req = new CreateBookingRequest();
        ReflectionTestUtils.setField(req, "listingId", LISTING_ID);
        ReflectionTestUtils.setField(req, "checkInDate", checkIn);
        ReflectionTestUtils.setField(req, "checkOutDate", checkOut);
        ReflectionTestUtils.setField(req, "numberOfGuests", guests);
        return req;
    }

    private Booking bookingWithStatus(BookingStatus status) {
        Booking b = Booking.builder()
                .listingId(LISTING_ID)
                .travelerId(TRAVELER_ID)
                .checkInDate(LocalDate.of(2026, 7, 1))
                .checkOutDate(LocalDate.of(2026, 7, 3))
                .numberOfGuests(2)
                .totalPrice(new BigDecimal("4000.00"))
                .build();
        ReflectionTestUtils.setField(b, "id", UUID.randomUUID());
        b.setStatus(status);
        return b;
    }
}
