package com.kyrgyzexplore.email;

import com.kyrgyzexplore.booking.Booking;
import com.kyrgyzexplore.booking.BookingRepository;
import com.kyrgyzexplore.config.SendGridConfig;
import com.kyrgyzexplore.listing.Listing;
import com.kyrgyzexplore.listing.ListingRepository;
import com.kyrgyzexplore.user.User;
import com.kyrgyzexplore.user.UserRepository;
import com.sendgrid.Method;
import com.sendgrid.Request;
import com.sendgrid.Response;
import com.sendgrid.SendGrid;
import com.sendgrid.helpers.mail.Mail;
import com.sendgrid.helpers.mail.objects.Content;
import com.sendgrid.helpers.mail.objects.Email;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.UUID;

/**
 * Sends transactional emails via SendGrid.
 *
 * WHY does EmailService fetch data itself (instead of receiving it as parameters)?
 * Callers like BookingService and AuthService already handle their own domain logic.
 * Passing raw domain objects or a long list of strings into every email call would
 * make those methods messy and tightly coupled. EmailService owning the data fetch
 * keeps call sites to a single line: emailService.sendBookingConfirmed(bookingId).
 *
 * WHY does send() catch exceptions instead of letting them propagate?
 * Email delivery is best-effort. If SendGrid is down or returns 429 (rate limit),
 * we must NOT roll back the booking transaction that triggered the email.
 * The booking is already saved — we log the failure and move on.
 *
 * WHY inline HTML instead of a template engine (Thymeleaf/FreeMarker)?
 * Template engines add a dependency and a resource file per email. For six simple
 * transactional emails, inline HTML generated by buildHtml() is easier to read,
 * easier to change, and has zero extra configuration.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class EmailService {

    private final SendGridConfig config;
    private final UserRepository userRepository;
    private final BookingRepository bookingRepository;
    private final ListingRepository listingRepository;

    public void sendWelcome(UUID userId) {
        userRepository.findById(userId).ifPresent(user -> {
            String html = buildHtml(
                    "Welcome to KyrgyzExplore, " + firstName(user) + "!",
                    "Your account has been created successfully.",
                    "Start exploring listings and book your next adventure in Kyrgyzstan.",
                    "<a href='https://kyrgyzexplore.com'>Open the app →</a>"
            );
            send(user.getEmail(), "Welcome to KyrgyzExplore!", html);
        });
    }

    public void sendBookingConfirmed(UUID bookingId) {
        withBookingData(bookingId, (booking, traveler, listing) -> {
            String html = buildHtml(
                    "Your booking is confirmed!",
                    "Hi " + firstName(traveler) + ", great news — the host has accepted your booking.",
                    "<strong>" + listing.getTitle() + "</strong>",
                    "Check-in: " + booking.getCheckInDate() + " &nbsp;|&nbsp; Check-out: " + booking.getCheckOutDate(),
                    "Guests: " + booking.getNumberOfGuests(),
                    "Total: " + formatPrice(booking.getTotalPrice(), listing.getCurrency()),
                    "You'll receive payment instructions shortly."
            );
            send(traveler.getEmail(), "Your booking is confirmed", html);
        });
    }

    public void sendBookingRejected(UUID bookingId) {
        withBookingData(bookingId, (booking, traveler, listing) -> {
            String reason = booking.getRejectionReason() != null
                    ? "Reason: " + booking.getRejectionReason()
                    : "The host did not provide a reason.";
            String html = buildHtml(
                    "Booking request declined",
                    "Hi " + firstName(traveler) + ", unfortunately your booking request was not accepted.",
                    "<strong>" + listing.getTitle() + "</strong>",
                    "Check-in: " + booking.getCheckInDate() + " &nbsp;|&nbsp; Check-out: " + booking.getCheckOutDate(),
                    reason,
                    "No charge has been made. Feel free to search for other available listings."
            );
            send(traveler.getEmail(), "Booking request declined", html);
        });
    }

    /**
     * @param cancelledByUserId the user who triggered the cancellation — used to
     *                          determine which party to email and what message to send.
     */
    public void sendBookingCancelled(UUID bookingId, UUID cancelledByUserId) {
        withBookingData(bookingId, (booking, traveler, listing) -> {
            boolean travelerCancelled = booking.getTravelerId().equals(cancelledByUserId);

            if (travelerCancelled) {
                // Notify the host that the traveler cancelled
                userRepository.findById(listing.getHostId()).ifPresent(host -> {
                    String html = buildHtml(
                            "Booking cancelled by traveler",
                            "Hi " + firstName(host) + ", the traveler has cancelled their booking.",
                            "<strong>" + listing.getTitle() + "</strong>",
                            "Check-in: " + booking.getCheckInDate() + " &nbsp;|&nbsp; Check-out: " + booking.getCheckOutDate(),
                            "The dates are now available again."
                    );
                    send(host.getEmail(), "Booking cancelled", html);
                });
            } else {
                // Host cancelled — notify the traveler
                String html = buildHtml(
                        "Your booking was cancelled by the host",
                        "Hi " + firstName(traveler) + ", unfortunately the host has cancelled your booking.",
                        "<strong>" + listing.getTitle() + "</strong>",
                        "Check-in: " + booking.getCheckInDate() + " &nbsp;|&nbsp; Check-out: " + booking.getCheckOutDate(),
                        "No charge has been made. We're sorry for the inconvenience — please search for another listing."
                );
                send(traveler.getEmail(), "Booking cancelled", html);
            }
        });
    }

    public void sendPaymentReceiptTraveler(UUID bookingId) {
        withBookingData(bookingId, (booking, traveler, listing) -> {
            String html = buildHtml(
                    "Payment confirmed — you're all set!",
                    "Hi " + firstName(traveler) + ", your payment has been received.",
                    "<strong>" + listing.getTitle() + "</strong> in " + listing.getCity(),
                    "Check-in: " + booking.getCheckInDate() + " &nbsp;|&nbsp; Check-out: " + booking.getCheckOutDate(),
                    "Amount paid: " + formatPrice(booking.getTotalPrice(), listing.getCurrency()),
                    "Booking ID: " + booking.getId(),
                    "Have a wonderful trip!"
            );
            send(traveler.getEmail(), "Payment confirmed — booking #" + shortId(booking.getId()), html);
        });
    }

    public void sendNewPaidBookingHost(UUID bookingId) {
        withBookingData(bookingId, (booking, traveler, listing) -> {
            userRepository.findById(listing.getHostId()).ifPresent(host -> {
                String html = buildHtml(
                        "New paid booking for " + listing.getTitle(),
                        "Hi " + firstName(host) + ", a traveler has paid for their booking.",
                        "Guest: " + fullName(traveler) + " (" + traveler.getEmail() + ")",
                        "Check-in: " + booking.getCheckInDate() + " &nbsp;|&nbsp; Check-out: " + booking.getCheckOutDate(),
                        "Guests: " + booking.getNumberOfGuests(),
                        "Total: " + formatPrice(booking.getTotalPrice(), listing.getCurrency()),
                        "Log in to the app to view the full booking details."
                );
                send(host.getEmail(), "New paid booking — " + listing.getTitle(), html);
            });
        });
    }

    // ---- internal helpers ----

    private void send(String toEmail, String subject, String htmlBody) {
        if (!config.isConfigured()) {
            log.debug("SendGrid not configured — skipping email to {}", toEmail);
            return;
        }
        try {
            Mail mail = new Mail(
                    new Email(config.getFromAddress(), config.getFromName()),
                    subject,
                    new Email(toEmail),
                    new Content("text/html", htmlBody)
            );
            SendGrid sg = new SendGrid(config.getApiKey());
            Request req = new Request();
            req.setMethod(Method.POST);
            req.setEndpoint("mail/send");
            req.setBody(mail.build());
            Response res = sg.api(req);
            if (res.getStatusCode() >= 400) {
                log.warn("SendGrid returned {} sending to {}: {}", res.getStatusCode(), toEmail, res.getBody());
            } else {
                log.debug("Email sent to {} — subject: {}", toEmail, subject);
            }
        } catch (IOException e) {
            log.error("Failed to send email to {}: {}", toEmail, e.getMessage());
        }
    }

    private String buildHtml(String heading, String... lines) {
        StringBuilder sb = new StringBuilder();
        sb.append("<div style='font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px'>");
        sb.append("<h2 style='color:#1a1a1a'>").append(heading).append("</h2>");
        for (String line : lines) {
            sb.append("<p style='color:#333;line-height:1.5'>").append(line).append("</p>");
        }
        sb.append("<hr style='border:none;border-top:1px solid #eee;margin:24px 0'>");
        sb.append("<p style='color:#999;font-size:12px'>KyrgyzExplore &mdash; Discover Kyrgyzstan</p>");
        sb.append("</div>");
        return sb.toString();
    }

    /**
     * Loads booking + traveler + listing, then runs the action.
     * Silently skips if any entity is missing — defensive coding for edge cases
     * (e.g. listing soft-deleted before email fires).
     */
    private void withBookingData(UUID bookingId, BookingEmailAction action) {
        Booking booking = bookingRepository.findById(bookingId).orElse(null);
        if (booking == null) return;
        User traveler = userRepository.findById(booking.getTravelerId()).orElse(null);
        if (traveler == null) return;
        Listing listing = listingRepository.findById(booking.getListingId()).orElse(null);
        if (listing == null) return;
        action.run(booking, traveler, listing);
    }

    @FunctionalInterface
    private interface BookingEmailAction {
        void run(Booking booking, User traveler, Listing listing);
    }

    private String firstName(User user) {
        return user.getFirstName() != null ? user.getFirstName() : user.getEmail();
    }

    private String fullName(User user) {
        if (user.getFirstName() == null) return user.getEmail();
        return user.getLastName() != null
                ? user.getFirstName() + " " + user.getLastName()
                : user.getFirstName();
    }

    private String formatPrice(BigDecimal amount, String currency) {
        return amount.stripTrailingZeros().toPlainString() + " " + currency;
    }

    private String shortId(UUID id) {
        return id.toString().substring(0, 8).toUpperCase();
    }
}
